### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by yummy-hat** [joshua-mae/HoleHelper#6]
Hello,

Thanks for making this! As someone who has used Hole via the executables and through the MDAnalysis plugin, I'm excited for something directly in VMD. Great idea.

Unfortunately, I'm not able to install the plugin, and the error message is very brief. I get:
```
The HoleHelper package could not be loaded
Unable to add menu HoleHelper
```
But when I try package require `HoleHelper`, it shows `1.0`. 

Any ideas on what could be going wrong? I'm running VMD 1.94a55 on RockyLinux 8. I get the same issue on 1.94a57 on Ubuntu.

**Comment by joshua-mae** [comment]
I messed up in the original readme for the setup, and I corrected it now; I definitely got confused with the too many things named holehelper but with different capitalization.  These are the correct lines to put in your .vmdrc.  Thanks for helping me correct the issue.
```
lappend auto_path /home/yourusername/HoleHelper/
vmd_install_extension holehelper holehelper_tk_cb Analysis/HoleHelper
```

**Comment by yummy-hat** [comment]
Thanks so much, that worked! Quick response is much appreciated. Using your suggestion, I was able to run on a single frame and see the output -- very cool. 

Your plugin is looking impressive, but I ran into a couple more issues:
- When I browse for a DCD file, none of my DCDs appear. So can't load them. 
- I navigated to my PSF/PDB files in the "File Options" panel, but I'm unable to load them. I get `Error: Needs proper pdb file`. I notice that there are a lot of different ways to trigger this output. Maybe more detailed outputs could be helpful for debugging? I found the conditional being triggered: if `{[file extension $primarypdb] != ".pdb"} {`. Turns out I had loaded the PSF into the PDB section, but I still think the logging could be improved here.. It worked when I properly loaded PDB into PDB and PSF into PSF.
- Small thing, but you have a typo: `PBC Wraping Condition (Centersel)` (should be wrapping)

But anyway, my main question: how can I run Hole on a trajectory using your plugin? I loaded a trajectory into VMD myself (not through the plugin), which does give me the option to `Run HOLE2 on Single Frame`. But not a trajectory. Any suggestions? 

Also, this is fairly niche (happy to make a new issue), but do you have a suggested way to run Hole on a membrane system with lipids? The lipids might form part of the pore I'm interested in, so I'd like to retain them in the calculation. I tried this before, and I had it running with my own custom .rad file. (This is a low-priority feature request, so don't worry too much about it)

**Comment by joshua-mae** [comment]
Thanks for all the comments.  I'm glad at least someone is using this, even if it is a year from when I wrote it haha.

1. The DCD file option uses a folder as its input.  So, it goes through all the DCD files in that folder even though it does not show them.  It really is just a way of selecting a folder with all your DCD files.  It might be a bad UI design, but I think I was limited with VMD/TCL.
2. Right, the error checking just checks the ends of the files and makes sure that they are placed into the right section.  Although, you are probably right with the fact that the error could be more verbose and even more extensive.
3. Good catch!
4. You just have to expand the window size vertically and it will have the button to run on a trajectory.  Another oversight from switching devices when working on this.
5. Go ahead and make a new issue.  This was originally built for BMCs, so I am unsure on how your situation would work (I am a CS student so forgive me if they are very similar).  I would be open to working on another plugin even if I can't implement it on this one so feel free to chat.

**Comment by yummy-hat** [comment]
Sorry I'm late to the party on this one! Could've definitely used your plugin a year ago.. I saw the plugin mentioned at a conference or I would've used it sooner. It's extremely convenient.

1. Okay, the file loading makes sense now! I didn't catch that it was trying to load all DCDs in a given folder. This is a little more convenient than just selecting a single trajectory, so I can't complain. It worked perfectly on my system. 
4. Great, thanks for addressing this. Your updated version shows the second button by default on my system.
5. Sounds good, I'll open a new issue. It might be too niche for you to include in the plugin. 

Again, big thanks for doing this. I have my pore profile for a whole trajectory now. You're saving me tons of time and effort with this plugin. Nice work!!
