### ISSUE TITLE
Input options

### ISSUE THREAD

**Issue by yummy-hat** [joshua-mae/HoleHelper#9]
Sorry for all the suggestions lately, but here are two more things that could be really helpful:
- Exposing the complete list of options to HOLE in the GUI (maybe in another "advanced" tab)
- Using the center-of-mass for an atomselection to set the center, and maybe choosing cvect based on two atomselections (which could update at each frame)

**Comment by joshua-mae** [comment]
I put in what I thought were the important options to include when running HOLE and used the MDAnalysis for reference.  I am pretty sure whatever I excluded would have no tangible effect on the results (at least it did not in our scenario).  I can look again to see if anything was missed and potentially consider another tab.  For the second point, I defaulted to Hole as you can tell, and I think that cpoint option is merely for visualization, but I assume I can just place the cpoint for each frame in its pdb.

**Comment by yummy-hat** [comment]
Sounds good, thanks for your efforts :)
